### ISSUE TITLE
Singleplayer crash, cobweb breaking speed(?) unexpected error.

### ISSUE THREAD

**Issue by Keoxxa** [Fourmisain/AxesAreWeapons#9]
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "state" is null
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.24)
	at io.github.fourmisain.axesareweapons.common.AxesAreWeaponsCommon.overrideCobWebMiningSpeed(AxesAreWeaponsCommon.java:21)
	at net.minecraft.item.Item.constant$beg000$cobWebsAreSpeed(Item:554)
	at net.minecraft.item.Item.getMiningSpeedMultiplier(Item:198)
	at net.minecraft.item.ItemStack.getMiningSpeedMultiplier(ItemStack:272)
	at net.minecraft.entity.player.PlayerInventory.getBlockBreakingSpeed(PlayerInventory:413)
	at net.minecraft.entity.player.PlayerEntity.handler$gbb000$gobberGetBlockBreakingSpeed(PlayerEntity:29879)
	at net.minecraft.entity.player.PlayerEntity.getBlockBreakingSpeed(PlayerEntity)
	at net.minecraft.block.AbstractBlock.handler$zzf000$getDestroySpeed(AbstractBlock:520)
	at net.minecraft.block.AbstractBlock.calcBlockBreakingDelta(AbstractBlock:383)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.calcBlockBreakingDelta(AbstractBlock:821)
	at net.minecraft.client.network.ClientPlayerInteractionManager.updateBlockBreakingProgress(ClientPlayerInteractionManager:241)
	at net.minecraft.client.MinecraftClient.handleBlockBreaking(MinecraftClient:1647)
	at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient:2013)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1829)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1135)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Full log (large modpack)
https://pastebin.com/EfgqLrDi

Not sure what's causing it, seems to happen consistently after just playing normally for a while but seems to only happen while bare hand breaking a block. This crash I was breaking a dirt block with my bare hand.
Disabling the mod seems to fix it, but I like using axes as weapons. Power over speed!

**Comment by Fourmisain** [comment]
Oh hold on, that mixin is only supposed to run on Fabric!

**Comment by Fourmisain** [comment]
This was indeed it.
New version is up on CurseForge (waiting for approval) and on Modrinth.
